# Copyright © 2022 Collabora Ltd
# SPDX-License-Identifier: MIT

progs = [
  'clear-color',
  'clear-fbo',
  'clear-fbo-scissor',
  'clear-fbo-tex',
  'clear-random',
  'clear-repeat',
  'clear-scissor',
  'clear-undefined',
  'createwin',
  'dlist-begin-call-end',
  'dlist-dangling',
  'dlist-degenerate',
  'dlist-edgeflag',
  'dlist-edgeflag-dangling',
  'dlist-flat-tri',
  'dlist-mat-tri',
  'dlist-recursive-call',
  'dlist-tri-flat-tri',
  'dlist-tri-mat-tri',
  'flat-clip',
  'fs-tri',
  'line',
  'line-clip',
  'line-cull',
  'line-flat',
  'lineloop',
  'lineloop-clip',
  'line-smooth',
  'line-stipple-wide',
  'linestrip',
  'linestrip-clip',
  'linestrip-flat-stipple',
  'linestrip-stipple',
  'linestrip-stipple-wide',
  'line-userclip',
  'line-userclip-clip',
  'line-userclip-nop',
  'line-userclip-nop-clip',
  'line-wide',
  'line-xor',
  'long-fixed-func',
  'pgon-mode',
  'point',
  'point-clip',
  'point-param',
  'point-sprite',
  'point-wide',
  'point-wide-smooth',
  'poly',
  'poly-flat',
  'poly-flat-clip',
  'poly-flat-unfilled-clip',
  'poly-unfilled',
  'quad',
  'quad-clip-all-vertices',
  'quad-clip',
  'quad-clip-nearplane',
  'quad-degenerate',
  'quad-flat',
  'quad-offset-factor',
  'quad-offset-unfilled',
  'quad-offset-units',
  'quads',
  'quadstrip',
  'quadstrip-clip',
  'quadstrip-cont',
  'quadstrip-flat',
  'quad-tex-2d',
  'quad-tex-3d',
  'quad-tex-alpha',
  'quad-tex-pbo',
  'quad-tex-sub',
  'quad-unfilled',
  'quad-unfilled-clip',
  'quad-unfilled-stipple',
  'readpixels',
  'sub-tex',
  'tex-quads',
  'tri-2101010',
  'tri-2101010-dlist',
  'tri-alpha',
  'tri-alpha-tex',
  'tri-blend',
  'tri-blend-color',
  'tri-blend-max',
  'tri-blend-min',
  'tri-blend-revsub',
  'tri-blend-sub',
  'tri',
  'tri-clear',
  'tri-clip',
  'tri-cull-both',
  'tri-cull',
  'tri-dlist',
  'tri-edgeflag',
  'tri-edgeflag-pv',
  'tri-edgeflag-array',
  'trifan',
  'trifan-flat',
  'trifan-flat-clip',
  'trifan-flat-unfilled-clip',
  'trifan-unfilled',
  'tri-fbo',
  'tri-fbo-tex',
  'tri-fbo-tex-mip',
  'tri-flat',
  'tri-flat-clip',
  'tri-fog',
  'tri-lit',
  'tri-lit-material',
  'tri-logicop-none',
  'tri-logicop-xor',
  'tri-mask-tri',
  'tri-multitex-vbo',
  'tri-orig',
  'tri-point-line-clipped',
  'tri-query',
  'tri-repeat',
  'tri-rotate',
  'tri-scissor-tri',
  'tri-square',
  'tri-stencil',
  'tri-stipple',
  'tristrip',
  'tristrip-clip',
  'tristrip-flat',
  'tri-tex-1d',
  'tri-tex-3d',
  'tri-tex',
  'tri-tex-stipple',
  'tri-tri',
  'tri-unfilled',
  'tri-unfilled-clip',
  'tri-unfilled-edgeflag',
  'tri-unfilled-fog',
  'tri-unfilled-point',
  'tri-unfilled-smooth',
  'tri-unfilled-tri',
  'tri-unfilled-tri-lit',
  'tri-unfilled-userclip',
  'tri-unfilled-userclip-stip',
  'tri-userclip',
  'tri-viewport',
  'tri-z-9',
  'tri-z',
  'tri-z-clip',
  'tri-z-eq',
]
foreach p : progs
  executable(
    p,
    files(p + '.c'),
    dependencies: [dep_gl, dep_glu, dep_glut, dep_m, idep_glad, idep_util],
    install: true,
  )
endforeach
