# Copyright © 2022 Collabora Ltd
# SPDX-License-Identifier: MIT

progs = [
  'aapoly',
  'aargb',
  'accanti',
  'accpersp',
  'alpha',
  'alpha3D',
  'anti',
  'bezcurve',
  'bezmesh',
  'checker',
  'clip',
  'colormat',
  'combiner',
  'cube',
  'cubemap',
  'depthcue',
  'dof',
  'double',
  'drawf',
  'feedback',
  'fog',
  'fogcoord',
  'font',
  'hello',
  'image',
  'light',
  'lines',
  'list',
  'material',
  'mipmap',
  'model',
  'movelight',
  'multisamp',
  'multitex',
  'mvarray',
  'nurbs',
  'pickdepth',
  'picksquare',
  'plane',
  'planet',
  'pointp',
  'polyoff',
  'polys',
  'quadric',
  'robot',
  'sccolorlight',
  'scene',
  'scenebamb',
  'sceneflat',
  'select',
  'shadowmap',
  'smooth',
  'stencil',
  'stroke',
  'surface',
  'surfpoints',
  'teaambient',
  'teapots',
  'tess',
  'tesswind',
  'texbind',
  'texgen',
  'texprox',
  'texsub',
  'texture3d',
  'texturesurf',
  'torus',
  'trim',
  'unproject',
  'varray',
  'wrap',
]
foreach p : progs
  executable(
    p,
    files(p + '.c'),
    dependencies: [dep_glu, dep_gl, dep_glut, dep_m, idep_glad, idep_util],
  )
endforeach
