# Copyright © 2022 Collabora Ltd
# SPDX-License-Identifier: MIT

install_data(
  'arch.png',
  'blinking-teapot.frag',
  'blinking-teapot.vert',
  'bw.png',
  'CH06-brick.frag',
  'CH06-brick.vert',
  'CH11-bumpmap.frag',
  'CH11-bumpmap.vert',
  'CH11-bumpmaptex.frag',
  'CH11-toyball.frag',
  'CH11-toyball.vert',
  'CH18-mandel.frag',
  'CH18-mandel.vert',
  'convolution.frag',
  'convolution.vert',
  'cubemap.frag',
  'geartrain.dat',
  'girl.png',
  'girl2.png',
  'isosurf.dat',
  'multitex.frag',
  'multitex.vert',
  'reflect.png',
  'reflect.vert',
  's128.png',
  'shadowtex.frag',
  'simple.vert',
  'simplex-noise.glsl',
  'skinning.frag',
  'skinning.vert',
  'terrain.dat',
  'tile.png',
  'tree2.png',
  'tree3.png',
  'wrs_logo.png',


  install_dir: get_option('datadir') / 'mesa-demos',
)
