# Copyright © 2022 Collabora Ltd
# SPDX-License-Identifier: MIT

install_data(
  'arch.png',
  'bw.png',
  'girl2.png',
  'girl.png',
  'reflect.png',
  's128.png',
  'tile.png',
  'tree2.png',
  'tree3.png',
  'wrs_logo.png',
  'geartrain.dat',
  'isosurf.dat',
  'terrain.dat',
  install_dir: get_option('datadir') / 'mesa-demos',
)
